version: 2.1
orbs:
  node: circleci/node@1.1.4
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          cache-key: yarn.lock
          steps:
            - run: yarn install --frozen-lockfile
      - run: yarn commitlint
      - run: yarn build
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test --ci
