/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Node".
 */
export type Node =
  | ForeignStyle
  | OvalShape
  | Gradient
  | GradientStop
  | StyleBasicFill
  | HotspotLayer
  | DocumentData
  | ForeignLayerStyle
  | AssetContainer
  | FreeformGroupLayout
  | AssetCollection
  | SliceLayer
  | ForeignTextStyle
  | StyleFill
  | GradientAsset
  | SharedTextStyleContainer
  | Layer
  | ExportFormat
  | GroupLayout
  | SymbolContainer
  | TextStyle
  | RectangleShape
  | ForeignSymbol
  | ShapePathLayer
  | OverrideValue
  | StarShape
  | GraphicsContextSettings
  | StyleBorderOptions
  | SymbolMaster
  | StyleBorder
  | PolygonShape
  | RulerData
  | Rect
  | ArtboardGroup
  | StylePart
  | ShapeGroup
  | CurvePoint
  | SharedObjectContainer
  | LayerGroup
  | TextLayer
  | LayoutGrid
  | Style
  | BaseGrid
  | ForeignObject
  | StyleBlur
  | ShapePath
  | StyledLayer
  | StyleInnerShadow
  | Symbol
  | Color
  | ExportPreset
  | StyleColorControls
  | SharedStyle
  | SimpleGrid
  | ColorAsset
  | SharedStyleContainer
  | ExportOptions
  | Page
  | OverrideProperty
  | TriangleShape
  | SymbolInstance
  | InferredGroupLayout
  | FlowConnection
  | ImageCollection
  | StyleShadow
  | SharedObject
  | BitmapLayer

/**
 * A document in the Schema
 */
export interface Document {
  _class?: 'document'
  assets?: AssetCollection
  colorSpace?: number
  currentPageIndex?: number
  do_objectID?: string
  foreignLayerStyles?: ForeignLayerStyle[]
  foreignSymbols?: ForeignSymbol[]
  foreignTextStyles?: ForeignTextStyle[]
  images?: {
    [k: string]: any
  }
  layerStyles?: SharedStyleContainer
  layerSymbols?: SymbolContainer
  layerTextStyles?: SharedTextStyleContainer
  pages?: Page[]
  userInfo?: {
    [k: string]: any
  }
  [k: string]: any
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "AssetCollection".
 */
export interface AssetCollection {
  _class?: 'assetCollection'
  colorAssets: ColorAsset[]
  colors?: {
    [k: string]: any
  }
  do_objectID?: string
  exportPresets?: ExportPreset[]
  gradientAssets: GradientAsset[]
  gradients?: {
    [k: string]: any
  }
  imageCollection: ImageCollection
  images: any[]
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ColorAsset".
 */
export interface ColorAsset {
  _class?: 'colorAsset'
  color: Color
  do_objectID?: string
  name?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Color".
 */
export interface Color {
  _class?: 'color'
  alpha?: number
  blue?: number
  do_objectID?: string
  green?: number
  red?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ExportPreset".
 */
export interface ExportPreset {
  _class?: 'exportPreset'
  do_objectID?: string
  exportFormats?: ExportFormat[]
  name?: string
  shouldApplyAutomatically: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ExportFormat".
 */
export interface ExportFormat {
  _class?: 'exportFormat'
  absoluteSize?: number
  do_objectID?: string
  fileFormat?: string
  name?: string
  namingScheme: number
  scale: number
  visibleScaleType: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "GradientAsset".
 */
export interface GradientAsset {
  _class?: 'gradientAsset'
  do_objectID?: string
  gradient: Gradient
  name?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Gradient".
 */
export interface Gradient {
  _class?: 'gradient'
  do_objectID?: string
  elipseLength?: number
  from: {
    [k: string]: any
  }
  gradientType?: number
  stops: GradientStop[]
  to: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "GradientStop".
 */
export interface GradientStop {
  _class?: 'gradientStop'
  color?: Color
  do_objectID?: string
  position?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ImageCollection".
 */
export interface ImageCollection {
  _class?: 'imageCollection'
  do_objectID?: string
  images: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ForeignLayerStyle".
 */
export interface ForeignLayerStyle {
  _class?: 'foreignLayerStyle'
  do_objectID?: string
  libraryID?: {
    [k: string]: any
  }
  localSharedStyle?: {
    [k: string]: any
  }
  remoteStyleID?: {
    [k: string]: any
  }
  sourceLibraryName?: {
    [k: string]: any
  }
  symbolPrivate?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ForeignSymbol".
 */
export interface ForeignSymbol {
  _class?: 'foreignSymbol'
  do_objectID?: string
  libraryID?: {
    [k: string]: any
  }
  originalMaster: SymbolMaster
  sourceLibraryName?: {
    [k: string]: any
  }
  symbolMaster: SymbolMaster
  symbolPrivate?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SymbolMaster".
 */
export interface SymbolMaster {
  _class?: 'symbolMaster'
  allowsOverrides?: boolean
  backgroundColor?: {
    [k: string]: any
  }
  booleanOperation?: number
  changeIdentifier?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  grid?: {
    [k: string]: any
  }
  groupLayout?: {
    [k: string]: any
  }
  hasBackgroundColor?: boolean
  hasClickThrough?: boolean
  hasClippingMask?: boolean
  horizontalRulerData?: {
    [k: string]: any
  }
  includeBackgroundColorInExport?: boolean
  includeBackgroundColorInInstance?: boolean
  includeInCloudUpload?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isFlowHome?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  layers?: {
    [k: string]: any
  }
  layout?: {
    [k: string]: any
  }
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  overrideProperties?: {
    [k: string]: any
  }
  presetDictionary?: {
    [k: string]: any
  }
  resizesContent?: boolean
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedObjectID?: {
    [k: string]: any
  }
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  symbolID?: string
  userInfo?: {
    [k: string]: any
  }
  verticalRulerData?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ForeignTextStyle".
 */
export interface ForeignTextStyle {
  _class?: 'foreignTextStyle'
  do_objectID?: string
  libraryID?: {
    [k: string]: any
  }
  localSharedStyle?: {
    [k: string]: any
  }
  remoteStyleID?: {
    [k: string]: any
  }
  sourceLibraryName?: {
    [k: string]: any
  }
  symbolPrivate?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SharedStyleContainer".
 */
export interface SharedStyleContainer {
  _class?: 'sharedStyleContainer'
  do_objectID?: string
  objects?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SymbolContainer".
 */
export interface SymbolContainer {
  _class?: 'symbolContainer'
  do_objectID?: string
  objects?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SharedTextStyleContainer".
 */
export interface SharedTextStyleContainer {
  _class?: 'sharedTextStyleContainer'
  do_objectID?: string
  objects?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Page".
 */
export interface Page {
  _class?: 'page'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  grid: SimpleGrid
  groupLayout?: {
    [k: string]: any
  }
  hasClickThrough?: boolean
  hasClippingMask?: boolean
  horizontalRulerData: RulerData
  includeInCloudUpload: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  layers?: {
    [k: string]: any
  }
  layout: LayoutGrid
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedObjectID?: {
    [k: string]: any
  }
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
  verticalRulerData: RulerData
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SimpleGrid".
 */
export interface SimpleGrid {
  _class?: 'simpleGrid'
  do_objectID?: string
  gridSize: number
  isEnabled?: boolean
  thickGridTimes: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "RulerData".
 */
export interface RulerData {
  _class?: 'rulerData'
  base?: number
  do_objectID?: string
  guides: any[]
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "LayoutGrid".
 */
export interface LayoutGrid {
  _class?: 'layoutGrid'
  columnWidth: number
  do_objectID?: string
  drawHorizontal?: boolean
  drawHorizontalLines?: boolean
  drawVertical: boolean
  gutterHeight: number
  guttersOutside: boolean
  gutterWidth: number
  horizontalOffset?: number
  isEnabled?: boolean
  numberOfColumns: number
  rowHeightMultiplication: number
  totalWidth: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ArtboardGroup".
 */
export interface ArtboardGroup {
  _class?: 'artboardGroup'
  backgroundColor: Color
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions: ExportOptions
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  grid: SimpleGrid
  groupLayout?: {
    [k: string]: any
  }
  hasBackgroundColor: boolean
  hasClickThrough?: boolean
  hasClippingMask?: boolean
  horizontalRulerData: RulerData
  includeBackgroundColorInExport: boolean
  includeInCloudUpload: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isFlowHome: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  layers?: {
    [k: string]: any
  }
  layout: LayoutGrid
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  presetDictionary?: {
    [k: string]: any
  }
  resizesContent: boolean
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedObjectID?: {
    [k: string]: any
  }
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
  verticalRulerData: RulerData
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ExportOptions".
 */
export interface ExportOptions {
  _class?: 'exportOptions'
  do_objectID?: string
  exportFormats: ExportFormat[]
  includedLayerIds: any[]
  layerOptions?: number
  shouldTrim?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "AssetContainer".
 */
export interface AssetContainer {
  _class?: 'assetContainer'
  do_objectID?: string
  name?: string
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "BaseGrid".
 */
export interface BaseGrid {
  _class?: 'baseGrid'
  do_objectID?: string
  isEnabled?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "BitmapLayer".
 */
export interface BitmapLayer {
  _class?: 'bitmap'
  booleanOperation?: number
  clippingMask: {
    [k: string]: any
  }
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  fillReplacesImage?: boolean
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  image?: {
    [k: string]: any
  }
  imageSHA?: {
    [k: string]: any
  }
  /**
   * The scale the image was imported with into Sketch. This can be derived on import from the DPI of the image or the suffixes (@2x) of the filename. On legacy documents defaults to 0, which is meant to be the default image DPI of 72.
   */
  intendedDPI?: number
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "CurvePoint".
 */
export interface CurvePoint {
  _class?: 'curvePoint'
  cornerRadius?: number
  curveFrom?: {
    [k: string]: any
  }
  curveMode?: number
  curveTo?: {
    [k: string]: any
  }
  do_objectID?: string
  hasCurveFrom?: boolean
  hasCurveTo?: boolean
  /**
   * The raw accessor for the receiver's location. Adjusting this does *not* affect curveFrom and curveTo; use -[MSCurvePoint movePointTo:] instead if you want those values to be kept consistent.
   */
  point?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "DocumentData".
 */
export interface DocumentData {
  _class?: 'documentData'
  assets: AssetCollection
  colorSpace: number
  currentPageIndex: number
  do_objectID?: string
  foreignLayerStyles: ForeignLayerStyle[]
  foreignSymbols: ForeignSymbol[]
  foreignTextStyles: ForeignTextStyle[]
  images?: {
    [k: string]: any
  }
  layerStyles: SharedStyleContainer
  layerSymbols: SymbolContainer
  layerTextStyles: SharedTextStyleContainer
  pages: Page[]
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "FlowConnection".
 */
export interface FlowConnection {
  _class?: 'flowConnection'
  animationType?: number
  destinationArtboardID?: string
  do_objectID?: string
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ForeignObject".
 */
export interface ForeignObject {
  _class?: 'foreignObject'
  do_objectID?: string
  libraryID?: string
  sourceLibraryName: string
  symbolPrivate?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ForeignStyle".
 */
export interface ForeignStyle {
  _class?: 'foreignStyle'
  do_objectID?: string
  libraryID?: {
    [k: string]: any
  }
  localSharedStyle: SharedStyle
  remoteStyleID: string
  sourceLibraryName?: {
    [k: string]: any
  }
  symbolPrivate?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SharedStyle".
 */
export interface SharedStyle {
  _class?: 'sharedStyle'
  do_objectID?: string
  name?: {
    [k: string]: any
  }
  value?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "FreeformGroupLayout".
 */
export interface FreeformGroupLayout {
  _class?: 'freeformGroupLayout'
  do_objectID?: string
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "GraphicsContextSettings".
 */
export interface GraphicsContextSettings {
  _class?: 'graphicsContextSettings'
  blendMode: number
  do_objectID?: string
  opacity: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "GroupLayout".
 */
export interface GroupLayout {
  _class?: 'groupLayout'
  do_objectID?: string
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "HotspotLayer".
 */
export interface HotspotLayer {
  _class?: 'hotspotLayer'
  booleanOperation?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  shouldBreakMaskChain?: boolean
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "InferredGroupLayout".
 */
export interface InferredGroupLayout {
  _class?: 'inferredGroupLayout'
  axis?: number
  do_objectID?: string
  layoutAnchor?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Layer".
 */
export interface Layer {
  _class?: 'layer'
  booleanOperation: number
  do_objectID?: string
  exportOptions: ExportOptions
  flow?: FlowConnection
  /**
   * The underlying storage for a layer's origin and size, and whether its proportions should be constrained
   */
  frame: {
    _class?: 'rect'
    constrainProportions?: boolean
    do_objectID?: string
    height?: number
    width?: number
    x?: number
    y?: number
  }
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked: boolean
  isVisible: boolean
  layerListExpandedType?: number
  name: string
  nameIsFixed?: boolean
  originalObjectID?: string
  resizingConstraint: number
  resizingType: number
  /**
   * The layer's rotation, specified in degrees. Rotation is applied about the center of \c frame
   */
  rotation?: number
  /**
   * When a shape is acting as a mask, this flag explicitly opts the receiver (and any folllowing layers) out of that masking, thereby breaking the chain.
   */
  shouldBreakMaskChain: boolean
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "LayerGroup".
 */
export interface LayerGroup {
  _class?: 'layerGroup'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  groupLayout: GroupLayout
  hasClickThrough: boolean
  hasClippingMask?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  layers: Layer[]
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedObjectID?: string
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}

/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "OvalShape".
 */
export interface OvalShape {
  _class?: 'ovalShape'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  edited?: boolean
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  isClosed?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  pointRadiusBehaviour?: number
  points?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleBasicFill".
 */
export interface StyleBasicFill {
  _class?: 'styleBasicFill'
  color?: Color
  contextSettings: GraphicsContextSettings
  do_objectID?: string
  fillType: number
  gradient: Gradient
  isEnabled?: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SliceLayer".
 */
export interface SliceLayer {
  _class?: 'sliceLayer'
  backgroundColor: Color
  booleanOperation?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasBackgroundColor: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  shouldBreakMaskChain?: boolean
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleFill".
 */
export interface StyleFill {
  _class?: 'styleFill'
  color?: {
    [k: string]: any
  }
  contextSettings?: {
    [k: string]: any
  }
  do_objectID?: string
  fillType?: number
  gradient?: {
    [k: string]: any
  }
  image?: {
    [k: string]: any
  }
  imageSHA?: {
    [k: string]: any
  }
  isEnabled?: boolean
  noiseIndex: number
  noiseIntensity?: number
  patternFillType: number
  patternTileScale: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "TextStyle".
 */
export interface TextStyle {
  _class?: 'textStyle'
  do_objectID?: string
  encodedAttributes?: {
    [k: string]: any
  }
  verticalAlignment?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "RectangleShape".
 */
export interface RectangleShape {
  _class?: 'rectangleShape'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  edited?: boolean
  exportOptions?: {
    [k: string]: any
  }
  fixedRadius: number
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  hasConvertedToNewRoundCorners?: boolean
  isClosed?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  pointRadiusBehaviour?: number
  points?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ShapePathLayer".
 */
export interface ShapePathLayer {
  _class?: 'shapePathLayer'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  /**
   * For shapes created using a preset (e.g. a rectangle or star), records whether the path is still in its original form, or has been edited by the user
   */
  edited?: boolean
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  isClosed?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  pointRadiusBehaviour: number
  points: CurvePoint[]
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "OverrideValue".
 */
export interface OverrideValue {
  _class?: 'overrideValue'
  do_objectID?: string
  overrideName: string
  value: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StarShape".
 */
export interface StarShape {
  _class?: 'starShape'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  edited?: boolean
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  isClosed?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  numberOfPoints: number
  originalObjectID?: {
    [k: string]: any
  }
  pointRadiusBehaviour?: number
  points?: {
    [k: string]: any
  }
  radius: number
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleBorderOptions".
 */
export interface StyleBorderOptions {
  _class?: 'styleBorderOptions'
  dashPattern: any[]
  do_objectID?: string
  isEnabled?: boolean
  lineCapStyle: number
  lineJoinStyle: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleBorder".
 */
export interface StyleBorder {
  _class?: 'styleBorder'
  color?: {
    [k: string]: any
  }
  contextSettings?: {
    [k: string]: any
  }
  do_objectID?: string
  fillType?: number
  gradient?: {
    [k: string]: any
  }
  isEnabled?: boolean
  position: number
  thickness: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "PolygonShape".
 */
export interface PolygonShape {
  _class?: 'polygonShape'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  edited?: boolean
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  isClosed?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  numberOfPoints: number
  originalObjectID?: {
    [k: string]: any
  }
  pointRadiusBehaviour?: number
  points?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Rect".
 */
export interface Rect {
  _class?: 'rect'
  constrainProportions?: boolean
  do_objectID?: string
  height?: number
  width?: number
  x?: number
  y?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StylePart".
 */
export interface StylePart {
  _class?: 'stylePart'
  do_objectID?: string
  isEnabled: boolean
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ShapeGroup".
 */
export interface ShapeGroup {
  _class?: 'shapeGroup'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  groupLayout?: {
    [k: string]: any
  }
  hasClickThrough?: boolean
  hasClippingMask?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  layers?: {
    [k: string]: any
  }
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedObjectID?: {
    [k: string]: any
  }
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
  windingRule?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SharedObjectContainer".
 */
export interface SharedObjectContainer {
  _class?: 'sharedObjectContainer'
  do_objectID?: string
  objects: SharedObject[]
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SharedObject".
 */
export interface SharedObject {
  _class?: 'sharedObject'
  do_objectID?: string
  name: string
  value?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "TextLayer".
 */
export interface TextLayer {
  _class?: 'textLayer'
  attributedString?: {
    [k: string]: any
  }
  automaticallyDrawOnUnderlyingPath?: boolean
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  dontSynchroniseWithSymbol?: boolean
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  glyphBounds?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  lineSpacingBehaviour: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  preview?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  textBehaviour: number
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Style".
 */
export interface Style {
  _class?: 'style'
  blur: StyleBlur
  borderOptions: StyleBorderOptions
  borders: StyleBorder[]
  colorControls: StyleColorControls
  contextSettings: GraphicsContextSettings
  do_objectID?: string
  endMarkerType?: number
  fills: StyleFill[]
  innerShadows: StyleInnerShadow[]
  miterLimit: number
  shadows: StyleShadow[]
  startMarkerType?: number
  textStyle?: TextStyle
  windingRule: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleBlur".
 */
export interface StyleBlur {
  _class?: 'styleBlur'
  center: {
    [k: string]: any
  }
  do_objectID?: string
  isEnabled?: boolean
  motionAngle: number
  radius: number
  saturation: number
  type?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleColorControls".
 */
export interface StyleColorControls {
  _class?: 'styleColorControls'
  brightness: number
  contrast: number
  do_objectID?: string
  hue: number
  isEnabled?: boolean
  saturation: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleInnerShadow".
 */
export interface StyleInnerShadow {
  _class?: 'styleInnerShadow'
  blurRadius?: number
  color?: {
    [k: string]: any
  }
  contextSettings?: {
    [k: string]: any
  }
  do_objectID?: string
  isEnabled?: boolean
  offsetX?: number
  offsetY?: number
  spread?: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyleShadow".
 */
export interface StyleShadow {
  _class?: 'styleShadow'
  blurRadius: number
  color: Color
  contextSettings: GraphicsContextSettings
  do_objectID?: string
  isEnabled?: boolean
  offsetX: number
  offsetY: number
  spread: number
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "ShapePath".
 */
export interface ShapePath {
  _class?: 'shapePath'
  do_objectID?: string
  isClosed?: boolean
  pointRadiusBehaviour: number
  points: CurvePoint[]
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "StyledLayer".
 */
export interface StyledLayer {
  _class?: 'styledLayer'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  /**
   * Whether the shape should act as a mask or not. If so, all layers _above_ this one are masked by it, up until we reach either the end of the group, or a layer with \c shouldBreakMaskChain turned on.
   */
  hasClippingMask?: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: string
  shouldBreakMaskChain?: boolean
  style: Style
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Symbol".
 */
export interface Symbol {
  _class?: 'symbol'
  do_objectID?: string
  name?: {
    [k: string]: any
  }
  value?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "OverrideProperty".
 */
export interface OverrideProperty {
  _class?: 'overrideProperty'
  canOverride: boolean
  do_objectID?: string
  /**
   * Whether this override value is currently being edited in the canvas.
   */
  overrideName: string
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "TriangleShape".
 */
export interface TriangleShape {
  _class?: 'triangleShape'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  edited?: boolean
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  isClosed?: boolean
  isEquilateral: boolean
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  pointRadiusBehaviour?: number
  points?: {
    [k: string]: any
  }
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  userInfo?: {
    [k: string]: any
  }
}
/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "SymbolInstance".
 */
export interface SymbolInstance {
  _class?: 'symbolInstance'
  booleanOperation?: number
  clippingMaskMode?: number
  do_objectID?: string
  exportOptions?: {
    [k: string]: any
  }
  flow?: {
    [k: string]: any
  }
  frame?: {
    [k: string]: any
  }
  hasClippingMask?: boolean
  horizontalSpacing?: number
  isFixedToViewport?: boolean
  isFlippedHorizontal?: boolean
  isFlippedVertical?: boolean
  isLocked?: boolean
  isVisible?: boolean
  layerListExpandedType?: number
  name?: {
    [k: string]: any
  }
  nameIsFixed?: boolean
  originalObjectID?: {
    [k: string]: any
  }
  overrideValues: OverrideValue[]
  resizingConstraint?: number
  resizingType?: number
  rotation?: number
  scale: number
  sharedStyleID?: {
    [k: string]: any
  }
  shouldBreakMaskChain?: boolean
  style?: {
    [k: string]: any
  }
  symbolID?: string
  userInfo?: {
    [k: string]: any
  }
  verticalSpacing?: number
}

/**
 * This interface was referenced by `Document`'s JSON-Schema
 * via the `definition` "Class".
 */
export const enum Class {
  documentData = 'documentData',
  groupLayout = 'groupLayout',
  sharedTextStyleContainer = 'sharedTextStyleContainer',
  foreignTextStyle = 'foreignTextStyle',
  foreignLayerStyle = 'foreignLayerStyle',
  shapePath = 'shapePath',
  style = 'style',
  symbol = 'symbol',
  foreignSymbol = 'foreignSymbol',
  shapeGroup = 'shapeGroup',
  gradientStop = 'gradientStop',
  starShape = 'starShape',
  gradient = 'gradient',
  styleBasicFill = 'styleBasicFill',
  hotspotLayer = 'hotspotLayer',
  foreignStyle = 'foreignStyle',
  shapePathLayer = 'shapePathLayer',
  assetCollection = 'assetCollection',
  sliceLayer = 'sliceLayer',
  triangleShape = 'triangleShape',
  modelObject = 'modelObject',
  inferredGroupLayout = 'inferredGroupLayout',
  overrideProperty = 'overrideProperty',
  rulerData = 'rulerData',
  symbolContainer = 'symbolContainer',
  symbolMaster = 'symbolMaster',
  styledLayer = 'styledLayer',
  curvePoint = 'curvePoint',
  styleBorderOptions = 'styleBorderOptions',
  symbolInstance = 'symbolInstance',
  textLayer = 'textLayer',
  exportFormat = 'exportFormat',
  rectangleShape = 'rectangleShape',
  ovalShape = 'ovalShape',
  stylePart = 'stylePart',
  gradientAsset = 'gradientAsset',
  styleBorder = 'styleBorder',
  exportPreset = 'exportPreset',
  flowConnection = 'flowConnection',
  imageCollection = 'imageCollection',
  graphicsContextSettings = 'graphicsContextSettings',
  sharedObject = 'sharedObject',
  sharedStyle = 'sharedStyle',
  rect = 'rect',
  layoutGrid = 'layoutGrid',
  color = 'color',
  colorAsset = 'colorAsset',
  textStyle = 'textStyle',
  styleColorControls = 'styleColorControls',
  freeformGroupLayout = 'freeformGroupLayout',
  layerGroup = 'layerGroup',
  baseGrid = 'baseGrid',
  exportOptions = 'exportOptions',
  bitmap = 'bitmap',
  foreignObject = 'foreignObject',
  assetContainer = 'assetContainer',
  polygonShape = 'polygonShape',
  sharedStyleContainer = 'sharedStyleContainer',
  sharedObjectContainer = 'sharedObjectContainer',
  styleBlur = 'styleBlur',
  layer = 'layer',
  page = 'page',
  simpleGrid = 'simpleGrid',
  styleFill = 'styleFill',
  styleInnerShadow = 'styleInnerShadow',
  styleShadow = 'styleShadow',
  overrideValue = 'overrideValue',
  artboardGroup = 'artboardGroup',
}
